[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Email notifications for form submissions
[[headers]]
  for = "/appointments"
  [headers.values]
    X-Frame-Options = "DENY"

# Form handling configuration
[forms]
  [forms.appointment]
    name = "appointment"
    to = "info@skylineautorepair.app"
    subject = "New Appointment Request - Skyline Auto Repair"
    from = "noreply@skylineautorepair.app"
    reply_to = "info@skylineautorepair.app"
    template = "email-template.html"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 